### PR TITLE
Fix compilation on latest Ubuntu related to boost-python

### PR DESCRIPTION
**Pull request by aroffringa**

### CODE REVIEW

**Comment by csbnw** [comment]
Installing LOFARBeam on Ubuntu 20.04 does not work by only updating the Ubuntu version in the `Dockerfile` that is part of this repository, some package names have changed. I am now fixing the `Dockerfile` to be able to reproduce the `boost-python` compilation problems.

**Comment by aroffringa** [comment]
Ok, go ahead. You can commit to this branch, I will wait with merging until you indicate you're ready.

**Comment by csbnw** [comment]
For reference, the build indeed doesn't work for Ubuntu 20.04 with the current master (f984931):
```
Step 27/30 : RUN cd build && cmake -DCMAKE_INSTALL_PREFIX=/usr -DPYTHON_EXECUTABLE=$(which python3) ../ && make -j16 && make install
 ---> Running in e520081f8ce5
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for sgemm_
-- Looking for sgemm_ - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for dgemm_
-- Looking for dgemm_ - found
-- Found BLAS: /usr/lib/x86_64-linux-gnu/libf77blas.so;/usr/lib/x86_64-linux-gnu/libatlas.so  
-- Looking for cheev_
-- Looking for cheev_ - not found
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
-- Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS) (found version "")
-- Found the following Casacore components: 
--   ms: /usr/lib/libcasa_ms.so
--   measures: /usr/lib/libcasa_measures.so
--   scimath: /usr/lib/libcasa_scimath.so
--   tables: /usr/lib/libcasa_tables.so
--   scimath_f: /usr/lib/libcasa_scimath_f.so
--   casa: /usr/lib/libcasa_casa.so
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Found PythonInterp: /usr/bin/python3 (found version "3.8.2") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found version "3.8.2") 
-- Build directory for Python extensions:        /src/build/lib/python3.8/site-packages
-- Installation directory for Python extensions: /usr/lib/python3.8/site-packages
Compiling Python 3.8 support. If this is not the intended target use 'DPYTHON_EXECUTABLE' to control.
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package):
  Could not find a package configuration file provided by "boost_python3"
  (requested version 1.71.0) with any of the following names:

    boost_python3Config.cmake
    boost_python3-config.cmake

  Add the installation prefix of "boost_python3" to CMAKE_PREFIX_PATH or set
  "boost_python3_DIR" to a directory containing one of the above files.  If
  "boost_python3" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:443 (find_package)
  CMakeLists.txt:83 (find_package)


-- Configuring incomplete, errors occurred!
See also "/src/build/CMakeFiles/CMakeOutput.log".
See also "/src/build/CMakeFiles/CMakeError.log".
The command '/bin/sh -c cd build && cmake -DCMAKE_INSTALL_PREFIX=/usr -DPYTHON_EXECUTABLE=$(which python3) ../ && make -j16 && make install' returned a non-zer
o code: 1
```

**Comment by aroffringa** [comment]
Indeed, that should be fixed with this PR.

**Pull request merged**
